Накопительная система лояльности «Гофермарт»
dlomanov/go-diploma-tpl pull request #1
Opened 2024-02-28 08:07 UTC by dlomanov

Первый PR для "корректировки курса". Система еще не готова.

2024-03-03 09:02 UTC, bambruysk requested changes
Очень хорошо. 
Обмазать тестами побольше и можно сдавать

2024-03-03 09:02 UTC, bambruysk commented on config/config.go
> +//go:embed config.yml
Очень хорошо написанный пакет конфигурации. 
Два замечания
1. //go:embed config.yml -  втягивает файл прямо в бинарник на этапе компиляции. Обычно мы конфиг файл используем для измения данных и поведения приложения без перекомпиляции.  Здесь же так не получится
2. Обчно конфиги пакета  ( ну например, логгер) кладем в тот же пакет, здесь же имеем только указатель на этот конфиг

2024-03-03 09:02 UTC, bambruysk commented on internal/entrypoints/http/middlewares/auth.go
> +		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
Здесь парям точно нужно такой двойной return?

2024-03-03 09:02 UTC, bambruysk commented on internal/usecase/balance.go
> +			return nil
если пользователь не найдет например, то вернется nil? наверное ошибка все таки?

2024-03-10 11:23 UTC, dlomanov commented on config/config.go
> +//go:embed config.yml
1. Да, config.yml в данном случае используется для дефолтных значений, которые можно переопределить переменными окружения или флагами. Подкладывать конфиг c текущим ТЗ мне показалось линим

2. Согласен, выделил конфиги для модулей pipeline и logging

2024-03-10 11:23 UTC, dlomanov commented on internal/entrypoints/http/middlewares/auth.go
> +		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
Не совсем понял. Посмотрел на реализацию middleware в chi, перекомпоновал тело функции

2024-03-10 11:23 UTC, dlomanov commented on internal/usecase/balance.go
> +			return nil
Согласен, нужно возвращать ошибку

2024-03-12 19:16 UTC, bambruysk approved these changes
Принято. Хорошо

2024-03-13 07:51 UTC, merged